import {
  env,
  pipeline,
  type TokenClassificationPipeline,
  type TokenClassificationSingle,
} from "@huggingface/transformers";
import { mapNerLabel } from "./labelMap";
import type { Span } from "../types";

/** Directory name under /models/ (see public/models/, generated by scripts/prepare-model). */
export const NER_MODEL_ID = "ner-ja";

export interface NerPipelineConfig {
  /** Model ID/repo to load. Defaults to NER_MODEL_ID (the PWA's bundled same-origin model). */
  modelId?: string;
  /** Defaults to false: fully local, same-origin model loading (see docs/CACHING_STRATEGY.md). */
  allowRemoteModels?: boolean;
  /** Only meaningful when allowRemoteModels is false. Defaults to "/models/". */
  localModelPath?: string;
  /**
   * Where onnxruntime-web loads its wasm runtime from. Defaults to "/ort/"
   * (a same-origin directory prefix). The standalone build instead passes an
   * explicit `{ wasm, mjs }` pair of blob: URLs for a runtime bundled
   * straight into the HTML file, so no wasm binary is fetched over the
   * network at all -- only the (necessarily much larger) NER model is.
   */
  wasmPaths?: string | { wasm?: string; mjs?: string };
  /**
   * A Web Cache API-shaped `{ match, put }` object (see
   * env.customCache in @huggingface/transformers) to use instead of the
   * browser's Cache Storage. Cache Storage's `Cache.put()` rejects `file:`
   * request URLs outright ("Request scheme 'file' is unsupported" --
   * confirmed by testing), so a standalone build meant to be opened directly
   * as a local file (no server) must supply its own cache -- see
   * standalone/src/indexedDbCache.ts, which is IndexedDB-backed and works
   * under file:. Only meaningful when allowRemoteModels is true; ignored
   * otherwise (env.useBrowserCache is only ever set for the remote-model
   * case -- see below).
   */
  customCache?: { match: (key: string) => Promise<Response | undefined>; put: (key: string, response: Response) => Promise<void> };
}

let pipelineConfig: NerPipelineConfig = {};

/**
 * Overrides the default (local-only, same-origin) model source. Must be
 * called before the first detectByNer/preloadNerModel call -- once loading
 * has started, later calls no longer affect that in-flight pipeline. The
 * PWA never calls this (its bundled same-origin model is the default); the
 * standalone single-file build uses it to point at the Hugging Face Hub and
 * a CDN-hosted onnxruntime-web wasm binary instead, since it ships no
 * same-origin model/wasm assets of its own.
 */
export function configureNerPipeline(config: NerPipelineConfig): void {
  pipelineConfig = config;
}

let envConfigured = false;
function applyEnvConfig(): void {
  if (envConfigured) return;
  const allowRemote = pipelineConfig.allowRemoteModels ?? false;
  // Force fully local, same-origin model loading unless a caller opted into
  // remote (Hugging Face Hub) models: no Hugging Face Hub calls, ever, from
  // the browser runtime (see docs/CACHING_STRATEGY.md).
  env.allowRemoteModels = allowRemote;
  env.allowLocalModels = !allowRemote;
  if (!allowRemote) {
    env.localModelPath = pipelineConfig.localModelPath ?? "/models/";
  }
  // Transformers.js has its own opaque, unversioned Cache Storage bucket
  // ("transformers-cache", see its hub.js) that it writes to regardless of
  // any custom Service Worker -- confirmed by inspecting Cache Storage
  // after a real load. The PWA disables it: left enabled, it silently
  // double-caches the ~278MB model (once there, once in this app's own
  // versioned model-assets cache -- see service-worker.ts/cache-config.ts),
  // and useOfflineStatus's readiness check has no way to know about it, so
  // the UI never reports "ready" even once the model is fully cached and
  // usable offline. This app's own SW cache is the deliberate, versioned
  // source of truth for the PWA (see docs/CACHING_STRATEGY.md). A
  // remote-model caller has no SW of its own, so it relies on this cache
  // instead for the "fetch once, then fully offline" property -- unless it
  // supplies its own customCache (see NerPipelineConfig.customCache above),
  // in which case that takes over instead (mutually exclusive with
  // useBrowserCache in transformers.js's own cache-selection order).
  if (pipelineConfig.customCache) {
    env.useCustomCache = true;
    env.customCache = pipelineConfig.customCache;
  } else {
    env.useBrowserCache = allowRemote;
  }
  // The PWA aliases "onnxruntime-web" to its wasm-only (non-WebGPU/jsep)
  // entry in vite.config.ts to roughly halve the mandatory first-load
  // download. That entry resolves its wasm binary's URL dynamically, which
  // Vite/Rollup can't statically bundle, so it's served as a same-origin
  // static asset and pointed at explicitly here.
  if (env.backends.onnx.wasm) {
    env.backends.onnx.wasm.wasmPaths = pipelineConfig.wasmPaths ?? "/ort/";
  }
  envConfigured = true;
}

let pipelinePromise: Promise<TokenClassificationPipeline> | null = null;

function loadPipeline(): Promise<TokenClassificationPipeline> {
  applyEnvConfig();
  if (!pipelinePromise) {
    pipelinePromise = pipeline<"token-classification">(
      "token-classification",
      pipelineConfig.modelId ?? NER_MODEL_ID,
      { dtype: "q8" },
    );
  }
  return pipelinePromise;
}

/** Below this score, a NER hit is treated as ambiguous rather than confident. */
export const NER_CONFIDENT_THRESHOLD = 0.75;
/** Below this score, a NER hit is discarded entirely (too likely to be noise). */
export const NER_FLOOR_THRESHOLD = 0.35;

export interface NerThresholds {
  confidentThreshold: number;
  floorThreshold: number;
}

export const DEFAULT_NER_THRESHOLDS: NerThresholds = {
  confidentThreshold: NER_CONFIDENT_THRESHOLD,
  floorThreshold: NER_FLOOR_THRESHOLD,
};

export interface NerDetection extends Span {
  /** True when confidence is between the floor and confident thresholds. */
  ambiguous: boolean;
  /** The exact substring matched, needed by the optional LLM disambiguation layer. */
  text: string;
}

/** Strips a leading BIO prefix ("B-", "I-") if present. */
function stripBioPrefix(label: string): string {
  return label.replace(/^[BI]-/, "");
}

/**
 * transformers.js's TokenClassificationPipeline never computes character
 * offsets at all (the underlying JS tokenizer has no offset-mapping support,
 * unlike Python's fast tokenizers -- see its own "TODO: Add support for
 * start and end" in pipelines.js) and returns one prediction per token
 * (unlike the Python HF pipeline's `aggregation_strategy`), so both offset
 * recovery and entity grouping have to happen here: assignCharOffsets()
 * re-locates each token's decoded text in the original string, then
 * consecutive tokens sharing the same bare entity type (B-/I- prefix
 * stripped) and forming a contiguous character range are merged into a
 * single span, using the run's minimum score as a conservative confidence
 * estimate.
 */

/**
 * Recovers each token's [start, end) character span by searching for its
 * decoded text in `text`, scanning forward from the end of the previous
 * match. This is a best-effort substitute for real offset-mapping (which
 * the JS tokenizer doesn't provide): the pipeline already strips
 * non-entity ("O") tokens out of the sequence before we see it, so gaps
 * between matches (untagged text) are expected and simply skipped over.
 * A token whose decoded text can't be found from the current cursor
 * onward (e.g. a tokenizer normalization mismatch) is left without an
 * offset and dropped by aggregateEntities.
 */
export function assignCharOffsets<T extends { word: string }>(
  text: string,
  tokens: T[],
): Array<T & { start?: number; end?: number }> {
  let cursor = 0;
  return tokens.map((token) => {
    const index = text.indexOf(token.word, cursor);
    if (index === -1) return token;
    cursor = index + token.word.length;
    return { ...token, start: index, end: cursor };
  });
}
export function aggregateEntities(
  tokens: Array<{ entity: string; score: number; start?: number; end?: number }>,
): Array<{ label: string; start: number; end: number; score: number }> {
  const groups: Array<{ label: string; start: number; end: number; score: number }> = [];

  for (const token of tokens) {
    if (token.start === undefined || token.end === undefined) continue;
    const bareLabel = stripBioPrefix(token.entity);
    if (bareLabel === "O" || bareLabel === "") continue;

    const last = groups[groups.length - 1];
    const isContinuation =
      last !== undefined && last.label === bareLabel && token.start <= last.end;

    if (isContinuation && last) {
      last.end = Math.max(last.end, token.end);
      last.score = Math.min(last.score, token.score);
    } else {
      groups.push({ label: bareLabel, start: token.start, end: token.end, score: token.score });
    }
  }

  return groups;
}

/**
 * The XLM-R tokenizer's decoded-word offset recovery (see assignCharOffsets)
 * has no way to fix a genuine per-character label flip-flop in the model's
 * own predictions -- e.g. a katakana name like "カナモリサナコ" where the
 * model tags "カナモ"+"サナ" as an entity but predicts "O" for the "リ" and
 * "コ" in between (surname/place-name ambiguity in the underlying
 * checkpoint). Left alone, aggregateEntities treats those as two separate
 * spans and the untagged middle characters are rendered as plain, unmasked
 * text in the output -- a real PII leak, not just a labeling quirk.
 *
 * This bridges that gap defensively: two entities separated by a short run
 * of non-whitespace, non-punctuation characters (almost certainly mid-word,
 * never a genuine boundary between two unrelated fields/sentences) are
 * merged into one span covering the whole run, so no fragment of a
 * partially-recognized entity is ever left unmasked. The merged span is
 * always flagged ambiguous regardless of score, since the bridge itself is
 * evidence the model's read on this text was inconsistent.
 */
const NER_BRIDGE_MAX_GAP = 2;

function isBridgeableGap(gapText: string): boolean {
  if (gapText.length === 0 || gapText.length > NER_BRIDGE_MAX_GAP) return false;
  // \s covers ASCII space/tab/newline; 　 is the full-width (Japanese)
  // space. Common separators/punctuation also block a bridge so this never
  // stitches together two genuinely distinct fields (e.g. tab-separated
  // spreadsheet columns) or two clauses either side of a comma/period.
  return !/[\s　,、。.!！?？:：;；「」『』()（）\-\/\\|]/.test(gapText);
}

export interface AggregatedEntity {
  label: string;
  start: number;
  end: number;
  score: number;
}

export function bridgeAdjacentEntities(
  text: string,
  entities: AggregatedEntity[],
): Array<AggregatedEntity & { bridged: boolean }> {
  const sorted = [...entities].sort((a, b) => a.start - b.start);
  const merged: Array<AggregatedEntity & { bridged: boolean }> = [];

  for (const entity of sorted) {
    const last = merged[merged.length - 1];
    if (last && entity.start > last.end && isBridgeableGap(text.slice(last.end, entity.start))) {
      last.label = entity.score > last.score ? entity.label : last.label;
      last.end = entity.end;
      last.score = Math.min(last.score, entity.score);
      last.bridged = true;
      continue;
    }
    merged.push({ ...entity, bridged: false });
  }

  return merged;
}

/**
 * bridgeAdjacentEntities only closes a gap *between* two recognized
 * entities; it can't help when the untagged remainder trails off the edge
 * of the text (or the edge of the next/previous entity) with nothing
 * recognized on the other side to bridge to -- e.g. "カナモリサナコ" tagged
 * as an entity only up through "...サナ", leaving the trailing "コ" as an
 * unmasked dangling character. This extends an entity's start/end into any
 * immediately-touching run of katakana, since a name/entity boundary that
 * itself falls mid-katakana is strong evidence the true word continues:
 * katakana never trails into a hiragana grammatical particle (です/でした/
 * さん, ...) the way kanji or rōmaji might, so this can't over-reach into
 * ordinary sentence continuation the way a same-script rule for kanji or
 * hiragana would. Extension is clamped to the neighboring entity's boundary
 * so it can never swallow a separately-recognized entity next to it.
 */
function isKatakana(ch: string | undefined): boolean {
  // U+30A0-U+30FF: the full katakana block, including the prolonged sound
  // mark "ー".
  return ch !== undefined && /^[゠-ヿ]$/.test(ch);
}

export function extendKatakanaRuns(
  text: string,
  entities: Array<AggregatedEntity & { bridged: boolean }>,
): Array<AggregatedEntity & { bridged: boolean }> {
  const sorted = [...entities].sort((a, b) => a.start - b.start);

  return sorted.map((entity, i) => {
    const prevEnd = sorted[i - 1]?.end ?? 0;
    const nextStart = sorted[i + 1]?.start ?? text.length;
    let { start, end } = entity;
    let extended = false;

    if (start < end && isKatakana(text[start])) {
      while (start > prevEnd && isKatakana(text[start - 1])) {
        start--;
        extended = true;
      }
    }
    if (start < end && isKatakana(text[end - 1])) {
      while (end < nextStart && isKatakana(text[end])) {
        end++;
        extended = true;
      }
    }

    return extended ? { ...entity, start, end, bridged: true } : entity;
  });
}

/**
 * The tokenizer truncates to the model's 512-token limit (see
 * `model_max_length` in public/models/ner-ja/tokenizer_config.json) with no
 * warning, so anything past that point is silently never scanned by NER on
 * long input. 400 characters is a conservative budget under that limit even
 * in the worst case of ~1 token per character (this tokenizer's SentencePiece
 * vocab mostly assigns whole Japanese characters their own token, so real
 * chunks run well under it).
 */
const NER_CHUNK_MAX_CHARS = 400;

/**
 * Splits `text` into chunks of at most `maxChars`, preferring to cut right
 * after a sentence-ending character (`。！？` or a newline) so a single
 * entity rarely straddles a chunk boundary. Falls back to a hard cut only
 * when one "sentence" by itself exceeds `maxChars`. The chunks always
 * concatenate back to exactly `text` -- this only decides where to cut, it
 * never drops or alters characters.
 */
export function chunkText(text: string, maxChars: number): Array<{ text: string; offset: number }> {
  if (text.length <= maxChars) return [{ text, offset: 0 }];

  const pieces: string[] = [];
  let pieceStart = 0;
  for (let i = 0; i < text.length; i++) {
    if ("。！？\n".includes(text[i])) {
      pieces.push(text.slice(pieceStart, i + 1));
      pieceStart = i + 1;
    }
  }
  if (pieceStart < text.length) pieces.push(text.slice(pieceStart));

  const chunks: Array<{ text: string; offset: number }> = [];
  let pos = 0;
  let current = "";
  let currentStart = 0;

  for (const piece of pieces) {
    if (piece.length > maxChars) {
      if (current) {
        chunks.push({ text: current, offset: currentStart });
        current = "";
      }
      for (let i = 0; i < piece.length; i += maxChars) {
        chunks.push({ text: piece.slice(i, i + maxChars), offset: pos + i });
      }
    } else if (current.length + piece.length > maxChars) {
      chunks.push({ text: current, offset: currentStart });
      current = piece;
      currentStart = pos;
    } else {
      if (current === "") currentStart = pos;
      current += piece;
    }
    pos += piece.length;
  }
  if (current) chunks.push({ text: current, offset: currentStart });

  return chunks;
}

export async function detectByNer(
  text: string,
  thresholds: NerThresholds = DEFAULT_NER_THRESHOLDS,
): Promise<NerDetection[]> {
  if (text.trim() === "") return [];
  const classify = await loadPipeline();

  const tokens: Array<{ entity: string; score: number; start?: number; end?: number }> = [];
  for (const chunk of chunkText(text, NER_CHUNK_MAX_CHARS)) {
    // Single-string input always yields the flat TokenClassificationSingle[]
    // form (never the batch TokenClassificationOutput[] form); the
    // pipeline's callback type doesn't encode that per-overload, hence the
    // cast. Chunks are run sequentially, not in parallel, since the ONNX
    // Runtime Web wasm session isn't guaranteed safe for concurrent Run()
    // calls.
    const rawTokens = (await classify(chunk.text)) as TokenClassificationSingle[];
    for (const token of assignCharOffsets(chunk.text, rawTokens)) {
      tokens.push({
        ...token,
        start: token.start === undefined ? undefined : token.start + chunk.offset,
        end: token.end === undefined ? undefined : token.end + chunk.offset,
      });
    }
  }

  const entities = extendKatakanaRuns(text, bridgeAdjacentEntities(text, aggregateEntities(tokens)));

  const detections: NerDetection[] = [];
  for (const entity of entities) {
    const category = mapNerLabel(entity.label);
    if (!category) continue;
    if (entity.score < thresholds.floorThreshold) continue;

    detections.push({
      start: entity.start,
      end: entity.end,
      category,
      source: "ner",
      confidence: entity.score,
      ambiguous: entity.bridged || entity.score < thresholds.confidentThreshold,
      text: text.slice(entity.start, entity.end),
    });
  }
  return detections;
}

/** Pre-warms the pipeline (model download/compile) without running inference. */
export function preloadNerModel(): Promise<TokenClassificationPipeline> {
  return loadPipeline();
}
