import {
  env,
  pipeline,
  type TokenClassificationPipeline,
  type TokenClassificationSingle,
} from "@huggingface/transformers";
import { mapNerLabel } from "./labelMap";
import type { Span } from "../types";

/** Directory name under /models/ (see public/models/, generated by scripts/prepare-model). */
export const NER_MODEL_ID = "ner-ja";

let configured = false;
function configureLocalOnlyModels(): void {
  if (configured) return;
  // Force fully local, same-origin model loading: no Hugging Face Hub calls,
  // ever, from the browser runtime (see docs/CACHING_STRATEGY.md).
  env.allowRemoteModels = false;
  env.allowLocalModels = true;
  env.localModelPath = "/models/";
  configured = true;
}

let pipelinePromise: Promise<TokenClassificationPipeline> | null = null;

function loadPipeline(): Promise<TokenClassificationPipeline> {
  configureLocalOnlyModels();
  if (!pipelinePromise) {
    pipelinePromise = pipeline<"token-classification">("token-classification", NER_MODEL_ID, {
      dtype: "q8",
    });
  }
  return pipelinePromise;
}

/** Below this score, a NER hit is treated as ambiguous rather than confident. */
export const NER_CONFIDENT_THRESHOLD = 0.75;
/** Below this score, a NER hit is discarded entirely (too likely to be noise). */
export const NER_FLOOR_THRESHOLD = 0.35;

export interface NerDetection extends Span {
  /** True when confidence is between the floor and confident thresholds. */
  ambiguous: boolean;
  /** The exact substring matched, needed by the optional LLM disambiguation layer. */
  text: string;
}

/** Strips a leading BIO prefix ("B-", "I-") if present. */
function stripBioPrefix(label: string): string {
  return label.replace(/^[BI]-/, "");
}

/**
 * transformers.js's token-classification pipeline returns one prediction per
 * token (unlike the Python HF pipeline's `aggregation_strategy`), so entity
 * grouping has to happen here: consecutive tokens sharing the same bare
 * entity type (B-/I- prefix stripped) and forming a contiguous character
 * range are merged into a single span, using the run's minimum score as a
 * conservative confidence estimate.
 */
export function aggregateEntities(
  tokens: Array<{ entity: string; score: number; start?: number; end?: number }>,
): Array<{ label: string; start: number; end: number; score: number }> {
  const groups: Array<{ label: string; start: number; end: number; score: number }> = [];

  for (const token of tokens) {
    if (token.start === undefined || token.end === undefined) continue;
    const bareLabel = stripBioPrefix(token.entity);
    if (bareLabel === "O" || bareLabel === "") continue;

    const last = groups[groups.length - 1];
    const isContinuation =
      last !== undefined && last.label === bareLabel && token.start <= last.end;

    if (isContinuation && last) {
      last.end = Math.max(last.end, token.end);
      last.score = Math.min(last.score, token.score);
    } else {
      groups.push({ label: bareLabel, start: token.start, end: token.end, score: token.score });
    }
  }

  return groups;
}

export async function detectByNer(text: string): Promise<NerDetection[]> {
  if (text.trim() === "") return [];
  const classify = await loadPipeline();
  // Single-string input always yields the flat TokenClassificationSingle[]
  // form (never the batch TokenClassificationOutput[] form); the pipeline's
  // callback type doesn't encode that per-overload, hence the cast.
  const tokens = (await classify(text)) as TokenClassificationSingle[];

  const entities = aggregateEntities(tokens);

  const detections: NerDetection[] = [];
  for (const entity of entities) {
    const category = mapNerLabel(entity.label);
    if (!category) continue;
    if (entity.score < NER_FLOOR_THRESHOLD) continue;

    detections.push({
      start: entity.start,
      end: entity.end,
      category,
      source: "ner",
      confidence: entity.score,
      ambiguous: entity.score < NER_CONFIDENT_THRESHOLD,
      text: text.slice(entity.start, entity.end),
    });
  }
  return detections;
}

/** Pre-warms the pipeline (model download/compile) without running inference. */
export function preloadNerModel(): Promise<TokenClassificationPipeline> {
  return loadPipeline();
}
